Make.delete_all
Make.create([
		{   id: 9, name: "آئودی"   },
		{   id: 60, name: "آریا"   },

		{   id: 56, name: "آلفارومئو"   },

		{   id: 10, name: "اپل"   },

		{   id: 88, name: "استین"   },

		{   id: 80, name: "اسمارت"   },

		{   id: 11, name: "الدزمبیل"   },

		{   id: 57, name: "ام جی"   },

		{   id: 12, name: "ام وی ام"   },

		{   id: 82, name: "ایسوزو"   },

		{   id: 92, name: "اینترنشنال"   },
		{   id: 79, name: "اینفینیتی"   },

		{   id: 1, name: "ب ام و"   },

		{   id: 97, name: "بایک"   },

		{   id: 96, name: "بسترن"   },

		{   id: 51, name: "بنز"   },
		
		{   id: 13, name: "بیوک"   },
		{   id: 14, name: "پاژن"   },
		{   id: 15, name: "پراید"   },
		{   id: 16, name: "پروتون"   },
		{   id: 52, name: "پژو"   },
		{   id: 65, name: "پلیموت"   },
		{   id: 17, name: "پورشه"   },
		{   id: 18, name: "پونتیاک"   },
		{   id: 62, name: "پیکان"   },
		{   id: 70, name: "تریومف"   },
		{   id: 53, name: "تویوتا"   },
		{   id: 68, name: "تیبا"   },
		{   id: 19, name: "جگوار"   },
		{   id: 85, name: "جک"   },
		{   id: 20, name: "جیپ"   },
		{   id: 86, name: "جیلی"   },
		{   id: 21, name: "چری"   },
		{   id: 25, name: "داتسون"   },
		{   id: 91, name: "دايهاتسو"   },
		{   id: 99, name: "دنا"   },
		{   id: 23, name: "دوج"   },
		{   id: 24, name: "دوو"   },
		{   id: 89, name: "رامبلر"   },
		{   id: 84, name: "رانا"   },
		{   id: 26, name: "رنو"   },
		{   id: 94, name: "روور"   },
		{   id: 67, name: "ساب"   },
		{   id: 77, name: "سانگ یانگ"   },
		{   id: 27, name: "سمند"   },
		{   id: 72, name: "سه آت"   },
		{   id: 29, name: "سوبارو"   },
		{   id: 28, name: "سوزوکی"   },
		{   id: 54, name: "سیتروئن"   },
		{   id: 73, name: "سیمرغ"   },
		{   id: 30, name: "سیناد"   },
		{   id: 31, name: "شورولت"   },
		{   id: 93, name: "فراری"   },
		{   id: 32, name: "فورد"   },
		{   id: 33, name: "فولکس"   },
		{   id: 34, name: "فیات"   },
		{   id: 64, name: "كاپرا"   },
		{   id: 35, name: "كادیلاك"   },
		{   id: 59, name: "كرایسلر"   },
		{   id: 37, name: "كیا"   },
		{   id: 83, name: "گریت وال"   },
		{   id: 90, name: "گک گونو"   },
		{   id: 38, name: "لادا"   },
		{   id: 95, name: "لامبورگینی"   },
		{   id: 39, name: "لانچیا"   },
		{   id: 41, name: "لندروور"   },
		{   id: 69, name: "لوبو"   },
		{   id: 40, name: "لکسوس"   },
		{   id: 42, name: "لیفان"   },
		{   id: 50, name: "لینکلن"   },
		{   id: 71, name: "مازراتی"   },
		{   id: 63, name: "مرکوری"   },
		{   id: 43, name: "مزدا"   },
		{   id: 46, name: "میتسوبیشی"   },
		{   id: 45, name: "مینی ماینر"   },
		{   id: 47, name: "نیسان"   },
		{   id: 58, name: "هامر"   },
		{   id: 98, name: "هولدن"   },
		{   id: 48, name: "هوندا"   },
		{   id: 78, name: "هیلمن"   },
		{   id: 49, name: "هیوندای"   },
		{   id: 87, name: "وانت"   },
		{   id: 81, name: "واکس هال"   },
		{   id: 55, name: "ولوو"   },
		{   id: 61, name: "ون"   }
])


CarModel.delete_all
CarModel.create([
# Audi
		{   make_id: 9, name: "A4"  },
		{   make_id: 9, name: "A6"  },
		{   make_id: 9, name: "Q5"  },
		{   make_id: 9, name: "Q7"  },
		{   make_id: 9, name: "R8"  },
		{   make_id: 9, name: "TT کوپه"  },

# ALfa romero
		{   make_id: 56, name: "جولیتا"   },
		{   make_id: 56, name: "میتو"   },

# opel
		{   make_id: 10, name: "آسترا"   },
		{   make_id: 10, name: "امگا"   },
		{   make_id: 10, name: "اینسیگنیا"   },
		{   make_id: 10, name: "رکورد"   },
		{   make_id: 10, name: "زافیرا"   },
		{   make_id: 10, name: "وکترا"   },
		{   make_id: 10, name: "کاپیتان"   },
		{   make_id: 10, name: "کالیبرا"   },
		{   make_id: 10, name: "کورسا اتوماتیک"   },
		{   make_id: 10, name: "کورسا دنده ای"   },

#استین
		{   make_id: 88, name: "دوون"   },
		{   make_id: 88, name: "مترو پلیتن"   },
		{   make_id: 88, name: "کمبریج"   },

# اسمارت
		{   make_id: 80, name: "رودستر"   },
		{   make_id: 80, name: "فورتو"   },

# الدزمبیل
		{   make_id: 11, name:  "سیرا"   },
		{   make_id: 11, name:  "کاتلاس"   },

# ام جی
		{   make_id: 57, name:  "350"   },
		{   make_id: 57, name:  "550"   },
		{   make_id: 57, name:  "6"   },

# ام وی ام
		{   make_id: 12, name:  "110  چهار سیلندر"   },
		{   make_id: 12, name:  "110 سه سیلندر"   },
		{   make_id: 12, name:  "315"   },
		{   make_id: 12, name:  "530"   },
		{   make_id: 12, name:  "X33"   },

# ایسوزو
		{   make_id: 82, name:  "تروپر"   },
		{   make_id: 82, name:  "وانت"   },

# اینترنشنال

# اینفینیتی
		{   make_id: 79, name:  "EX"   },
		{   make_id: 79, name:  "FX"   },
 
# "ب ام و" 
		{   make_id: 1, name: "118i"   },
		{   make_id: 1, name: "120i"   },
		{   make_id: 1, name: "120i کروک"   },
		{   make_id: 1, name: "125i کروک"   },
		{   make_id: 1, name: "125i کوپه"   },
		{   make_id: 1, name: "135i کروک"   },
		{   make_id: 1, name: "135i کوپه"   },
		{   make_id: 1, name: "2002"   },
		{   make_id: 1, name: "316i"   },
		{   make_id: 1, name: "318i"   },
		{   make_id: 1, name: "320i"   },
		{   make_id: 1, name: "320i کروک"   },
		{   make_id: 1, name: "320i کوپه"   },
		{   make_id: 1, name: "325i"   },
		{   make_id: 1, name: "325i کروک"   },
		{   make_id: 1, name: "325i کوپه"   },
		{   make_id: 1, name: "328i"   },
		{   make_id: 1, name: "330i"   },
		{   make_id: 1, name: "330i کروک"   },
		{   make_id: 1, name: "330i کوپه"   },
		{   make_id: 1, name: "335i"   },
		{   make_id: 1, name: "335i کروک"   },
		{   make_id: 1, name: "335i کوپه"   },
		{   make_id: 1, name: "518i"   },
		{   make_id: 1, name: "520i"   },
		{   make_id: 1, name: "523i"   },
		{   make_id: 1, name: "525i"   },
		{   make_id: 1, name: "528i"   },
		{   make_id: 1, name: "530i"   },
		{   make_id: 1, name: "535i"   },
		{   make_id: 1, name: "540i"   },
		{   make_id: 1, name: "545i"   },
		{   make_id: 1, name: "550i"   },
		{   make_id: 1, name: "630i کروک"   },
		{   make_id: 1, name: "630i کوپه"   },
		{   make_id: 1, name: "640i کوپه"   },
		{   make_id: 1, name: "650i گرن کوپه"   },
		{   make_id: 1, name: "650i کروک"   },
		{   make_id: 1, name: "650i کوپه"   },
		{   make_id: 1, name: "730i"   },
		{   make_id: 1, name: "730Li"   },
		{   make_id: 1, name: "733"   },
		{   make_id: 1, name: "735i"   },
		{   make_id: 1, name: "735Li"   },
		{   make_id: 1, name: "740i"   },
		{   make_id: 1, name: "740Li"   },
		{   make_id: 1, name: "745i"   },
		{   make_id: 1, name: "750i"   },
		{   make_id: 1, name: "750Li"   },
		{   make_id: 1, name: "850i"   },
		{   make_id: 1, name: "CS 3.0"   },
		{   make_id: 1, name: "M3"   },
		{   make_id: 1, name: "M5"   },
		{   make_id: 1, name: "M6"   },
		{   make_id: 1, name: "X1 1.8L"   },
		{   make_id: 1, name: "X1 2.0L"   },
		{   make_id: 1, name: "X1 2.8L"   },
		{   make_id: 1, name: "X3 2.0L"   },
		{   make_id: 1, name: "X3 2.5L"   },
		{   make_id: 1, name: "X3 2.8L"   },
		{   make_id: 1, name: "X3 3.0L"   },
		{   make_id: 1, name: "X3 3.5L"   },
		{   make_id: 1, name: "X5"   },
		{   make_id: 1, name: "X6  3.5L"   },
		{   make_id: 1, name: "X6 5.0L"   },
		{   make_id: 1, name: "Z3"   },
		{   make_id: 1, name: "Z4 20i"   },
		{   make_id: 1, name: "Z4 23i"   },
		{   make_id: 1, name: "Z4 28i"   },
		{   make_id: 1, name: "Z4 30i"   },
		{   make_id: 1, name: "Z4 35i"   },
		{   make_id: 1, name: "کلاسیک"   },

# بایک
		{   make_id: 97, name: "سابرینا صندوقدار"   },
		{   make_id: 97, name: "سابرینا هاچ بک"   },
		{   make_id: 97, name: "سنوا"   },

# بسترن
		{   make_id: 96, name: "B50"   },

# بنز
		{   make_id: 51, name: "A150"   },
		{   make_id: 51, name: "A160"   },
		{   make_id: 51, name: "A170"   },
		{   make_id: 51, name: "A180"   },
		{   make_id: 51, name: "A200"   },
		{   make_id: 51, name: "A200 Turbo"   },
		{   make_id: 51, name: "B150"   },
		{   make_id: 51, name: "B160"   },
		{   make_id: 51, name: "B170"   },
		{   make_id: 51, name: "B180"   },
		{   make_id: 51, name: "B200"   },
		{   make_id: 51, name: "B200 Turbo"   },
		{   make_id: 51, name: "C180"   },
		{   make_id: 51, name: "C190"   },
		{   make_id: 51, name: "C200"   },
		{   make_id: 51, name: "C220"   },
		{   make_id: 51, name: "C230"   },
		{   make_id: 51, name: "C240"   },
		{   make_id: 51, name: "C250"   },
		{   make_id: 51, name: "C280"   },
		{   make_id: 51, name: "C300"   },
		{   make_id: 51, name: "C350"   },
		{   make_id: 51, name: "CE230"   },
		{   make_id: 51, name: "CL500"   },
		{   make_id: 51, name: "CL600"   },
		{   make_id: 51, name: "CLK200"   },
		{   make_id: 51, name: "CLK240"   },
		{   make_id: 51, name: "CLK280"   },
		{   make_id: 51, name: "CLK320"   },
		{   make_id: 51, name: "CLK350"   },
		{   make_id: 51, name: "CLS350"   },
		{   make_id: 51, name: "CLS500"   },
		{   make_id: 51, name: "CLS550"   },
		{   make_id: 51, name: "E190"   },
		{   make_id: 51, name: "E200"   },
		{   make_id: 51, name: "E200 (مونتاژ)"   },
		{   make_id: 51, name: "E200 (کوپه)"   },
		{   make_id: 51, name: "E220"   },
		{   make_id: 51, name: "E230"   },
		{   make_id: 51, name: "E230 (مونتاژ)"   },
		{   make_id: 51, name: "E240"   },
		{   make_id: 51, name: "E250"   },
		{   make_id: 51, name: "E260"   },
		{   make_id: 51, name: "E280"   },
		{   make_id: 51, name: "E280 (مونتاژ)"   },
		{   make_id: 51, name: "E300"   },
		{   make_id: 51, name: "E320"   },
		{   make_id: 51, name: "E350"   },
		{   make_id: 51, name: "E350 (مونتاژ)"   },
		{   make_id: 51, name: "E350 کروک"   },
		{   make_id: 51, name: "E350 کوپه"   },
		{   make_id: 51, name: "G230"   },
		{   make_id: 51, name: "G280"   },
		{   make_id: 51, name: "G350"   },
		{   make_id: 51, name: "G500"   },
		{   make_id: 51, name: "GLK280"   },
		{   make_id: 51, name: "GLK300"   },
		{   make_id: 51, name: "GLK350"   },
		{   make_id: 51, name: "ML320"   },
		{   make_id: 51, name: "ML350"   },
		{   make_id: 51, name: "ML500"   },
		{   make_id: 51, name: "ML63"   },
		{   make_id: 51, name: "S170"   },
		{   make_id: 51, name: "S230"   },
		{   make_id: 51, name: "S250"   },
		{   make_id: 51, name: "S280"   },
		{   make_id: 51, name: "S300"   },
		{   make_id: 51, name: "S320"   },
		{   make_id: 51, name: "S350"   },
		{   make_id: 51, name: "S420"   },
		{   make_id: 51, name: "S450"   },
		{   make_id: 51, name: "S500"   },
		{   make_id: 51, name: "S550"   },
		{   make_id: 51, name: "S600"   },
		{   make_id: 51, name: "S63"   },
		{   make_id: 51, name: "S65"   },
		{   make_id: 51, name: "SEC560"   },
		{   make_id: 51, name: "SEL450"   },
		{   make_id: 51, name: "SL350"   },
		{   make_id: 51, name: "SL500"   },
		{   make_id: 51, name: "SL600"   },
		{   make_id: 51, name: "SLC350"   },
		{   make_id: 51, name: "SLC450"   },
		{   make_id: 51, name: "SLK200"   },
		{   make_id: 51, name: "SLK230"   },
		{   make_id: 51, name: "SLK280"   },
		{   make_id: 51, name: "SLK350"   },
		{   make_id: 51, name: "SLK55"   },
		{   make_id: 51, name: "SLR"   },
		{   make_id: 51, name: "SLS"   },
		{   make_id: 51, name: "ون"   },
		{   make_id: 51, name: "ون (مونتاژ)"   },
		{   make_id: 51, name: "ویانو"   },
		{   make_id: 51, name: "کلاس SE"   },
		{   make_id: 51, name: "کلاس SEL"   },
		{   make_id: 51, name: "کلاسیک"   },
		{   make_id: 51, name: "یونیماگ"   }
])
